export const appRoutes = {
  HOME: "/",
  COMPETITIONS: "/competitions",
  AEXAMFORMS: "/admin/examforms",
  CLASSES: "/classes",
  DETAIL: "/detail",
  ACLASSES: "/admin/classes",
  ACOURSES: "/admin/courses",
  AEMPLOYEES: "/admin/employees",
  ASTUDENTS: "/admin/students",
  ACOMPETITIONS: "/admin/competitions",
  ACOMPETITIONS_DETAIL: "/admin/competitions/:id",
  AROUNDS: "/admin/rounds",
  LOGIN: "/login",
};
