export const appRoutes = {
	HOME: '/',
	COMPETITIONS: '/competitions',
	AEXAMFORMS: '/admin/examforms',
	ADASHBOARD: '/admin/dashboard',
	CLASSES: '/classes',
	COMPETITION_DETAIL: '/competition/:id',
	COMPETITION_RESULT: '/competitions/:id/result',
	MYCOMPETITION: '/mycompetition',
	// DETAIL: "/detail",
	ACLASSES: '/admin/classes',
	ACOURSES: '/admin/courses',
	AEMPLOYEES: '/admin/employees',
	ASTUDENTS: '/admin/students',
	ACOMPETITIONS: '/admin/competitions',
	ACOMPETITIONS_DETAIL: '/admin/competitions/:id',
	AROUNDS: '/admin/rounds',
	AREGISTER: '/admin/register',
	ASCORE: '/admin/scores',
	LOGIN: '/login',
	TROUND: '/teacher/rounds',
	TSCORE: '/teacher/scores/:roundId',
	SCORE: '/scores',
};
