export const appRoutes = {
  HOME: "/",
  COMPETITIONS: "/competitions",
  AEXAMFORMS: "/admin/examforms",
  CLASSES: "/classes",
  COMPETITION_DETAIL: "/competition/:id",
  MYCOMPETITION: "/mycompetition",
  // DETAIL: "/detail",
  ACLASSES: "/admin/classes",
  ACOURSES: "/admin/courses",
  AEMPLOYEES: "/admin/employees",
  ASTUDENTS: "/admin/students",
  ACOMPETITIONS: "/admin/competitions",
  ACOMPETITIONS_DETAIL: "/admin/competitions/:id",
  AROUNDS: "/admin/rounds",
  AREGISTER: "/admin/register",
  LOGIN: "/login",
  TROUND: "/teacher/rounds",
  TSCORE: "/teacher/scores/:roundId",
};
